# permissions for end users to edit ec2instances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ec2instance-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aws-ec2-instance
    app.kubernetes.io/part-of: aws-ec2-instance
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-editor-role
rules:
- apiGroups:
  - aws.kraken-iac.eoinfennessy.com
  resources:
  - ec2instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.kraken-iac.eoinfennessy.com
  resources:
  - ec2instances/status
  verbs:
  - get
