---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - aws.kraken-iac.eoinfennessy.com
  resources:
  - ec2instances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.kraken-iac.eoinfennessy.com
  resources:
  - ec2instances/finalizers
  verbs:
  - update
- apiGroups:
  - aws.kraken-iac.eoinfennessy.com
  resources:
  - ec2instances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
