apiVersion: core.kraken-iac.eoinfennessy.com/v1alpha1
kind: StateDeclaration
metadata:
  labels:
    app.kubernetes.io/name: statedeclaration
    app.kubernetes.io/instance: statedeclaration-sample
    app.kubernetes.io/part-of: kraken
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kraken
  name: ec2instance-my-instance
spec:
  data:
    instances:
      - instanceType: t2.nano
        minCount: 1