apiVersion: aws.kraken-iac.eoinfennessy.com/v1alpha1
kind: EC2Instance
metadata:
  labels:
    app.kubernetes.io/name: ec2instance
    app.kubernetes.io/instance: ec2instance-sample
    app.kubernetes.io/part-of: aws-ec2-instance
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aws-ec2-instance
  name: ec2instance-sample
spec:
  imageID:
    valueFrom:
      configMap:
        name: my-ec2-config
        key: imageID
  instanceType:
    valueFrom:
      krakenResource:
        kind: ec2instance
        name: my-instance
        path: instances.0.instanceType
  maxCount:
    valueFrom:
      configMap:
        name: my-ec2-config
        key: maxCount
  minCount:
    valueFrom:
      krakenResource:
        kind: ec2instance
        name: my-instance
        path: instances.0.minCount
